[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lungnoodle.aether"
version = "@Aether_VERSION@"
description = "Aether library of routines for modelling the lung."
readme = { file = "README.rst", content-type = "text/x-rst" }
authors = [    { name = "Lung Group, Auckland Bioengineering Institute.", email = "m.tawhai@auckland.ac.nz" }]
license = { file = "LICENCE.txt" }
urls = { homepage = "https://lung.bioeng.auckland.ac.nz/" }
classifiers = [
@CLASSIFIERS@
]
dependencies = [
  'intel-fortran-rt; platform_system == "Windows"',
]

[tool.setuptools]
packages = ["aether"]

[tool.setuptools.package-data]
aether = ["*.so", "*.pyd", "*.dylib", "*.dll"]
